spring.application.name=quicklook

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/quicklook_db
spring.datasource.username=postgres
spring.datasource.password=Holynight

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

quicklook.jwt.secret=M5x92!zQkWB#pvJNRAt7DYuTe^j93pLs
quicklook.jwt.expiration=86400000